server:
  port: 19097

spring:
  application:
    name: payment-service

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: payment-service
      service: payment-service
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}
  tracing:
    sampling:
      probability: 1.0

common:
  kafka:
    bootstrap-servers: "${KAFKA_BOOTSTRAP_SERVERS}"
  trust-package: "com.taken_seat.common_service.message"

kafka:
  topic:
    payment-request: payment.request
    payment-response: payment.response
    refund-request: payment.refund.request
    refund-response: payment.refund.response
  consumer:
    group-id: payment-service


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}


logging:
  loki:
    url: ${LOKI_URL}

toss:
  secret-key: ${TOSS_SECRET_KEY}