spring:
  application:
    name: common-service

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  metrics:
    tags:
      service: ${spring.application.name}
