server:
  port: 19098

spring:
  application:
    name: review-service

  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans" # zipkin에서 정해진 엔드포인트
  tracing:
    sampling:
      probability: 1.0

common:
  trust-package: "com.taken_seat.common_service.message"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

feign:
  client:
    performance:
      name: performance-service
      url:
        http://localhost:19096/api/v1/performances
    booking:
      name: booking-service
      url:
        http://localhost:19095/api/v1/bookings