spring:
  application:
    name: coupon-service
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql

common:
  kafka:
    bootstrap-servers: "${KAFKA_BOOTSTRAP_SERVERS}"
  trust-package: "com.taken_seat.common_service.message"


server:
  port: 19093

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

kafka:
  topic:
    coupon-request-user: coupon.request.user
  consumer:
    group-id: auth-service

management:
  metrics:
    tags:
      application: coupon-service
      service: coupon-service
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  loki:
    url: ${LOKI_URL}