spring:
  application:
    name: gateway-service
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auths/**, /api/v1/users/**, /api/v2/users/**, /auth-service/v3/api-docs
          filters:
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}

        - id: coupon-service
          uri: lb://coupon-service
          predicates:
            - Path=/api/v1/coupons/**, /coupon-service/v3/api-docs
          filters:
            - RewritePath=/coupon-service/(?<segment>.*), /$\{segment}

        - id: performance-service
          uri: lb://performance-service
          predicates:
            - Path=/api/v1/performances/**, /api/v1/performancehalls/**, /api/v1/performencetickets/**, /api/v1/seats/**, /performance-service/v3/api-docs
          filters:
            - RewritePath=/performance-service/(?<segment>.*), /$\{segment}

        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/v1/bookings/**, /api/v1/tickets/**, /booking-service/v3/api-docs
          filters:
            - RewritePath=/booking-service/(?<segment>.*), /$\{segment}

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**, /payment-service/v3/api-docs
          filters:
            - RewritePath=/payment-service/(?<segment>.*), /$\{segment}

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/v1/reviews/**, /review-service/v3/api-docs
          filters:
            - RewritePath=/review-service/(?<segment>.*), /$\{segment}

        - id: queue-service
          uri: lb://queue-service
          predicates:
            - Path=/api/v1/queue/**, /queue-service/v3/api-docs
          filters:
            - RewritePath=/queue-service/(?<segment>.*), /$\{segment}

      discovery:
        locator:
          enabled: true
      #default-filters:

server:
  port: 19091

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

service:
  jwt:
    secret:
      key: ${JWT_SECRET}


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /docs
    urls:
      - name: auth-service
        url: /auth-service/v3/api-docs

      - name: coupon-service
        url: /coupon-service/v3/api-docs

      - name: performance-service
        url: /performance-service/v3/api-docs

      - name: booking-service
        url: /booking-service/v3/api-docs

      - name: payment-service
        url: /payment-service/v3/api-docs

      - name: review-service
        url: /review-service/v3/api-docs

      - name: queue-service
        url: /queue-service/v3/api-docs

management:
  metrics:
    tags:
      application: gateway-service
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: '*'



logging:
  loki:
    url: ${LOKI_URL}