spring:
  application:
    name: queue-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  data:
    redis:
      host: localhost
      port: 6379
      password: systempass

server:
  port: 19094

service:
  jwt:
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"
  admin:
    code: toolatebro

kafka:
  topic:
    queue-request: waitingQueue.request
    queue-result: waitingQueue.request


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:19090/eureka/

common:
  trust-package: "com.taken_seat.common_service.message"


logging:
  loki:
    url: ${LOKI_URL}