spring:
  application:
    name: queue-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  data:
    redis:
      host: localhost
      port: 6379
      password: systempass

server:
  port: 19094

service:
  jwt:
    secret-key: ${JWT_SECRET}
  admin:
    code: toolatebro

kafka:
  topic:
    queue-request: waitingQueue.request
    queue-result: waitingQueue.request


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  metrics:
    tags:
      application: queue-service
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: '*'

common:
  trust-package: "com.taken_seat.common_service.message"


logging:
  loki:
    url: ${LOKI_URL}