spring:
  application:
    name: performance-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

server:
  port: 19096

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: performance-service

  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:19090/eureka/

common:
  trust-package: "com.taken_seat.common_service.message"


logging:
  loki:
    url: ${LOKI_URL}


# 로컬
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
