name: 이선좌 - Multi-Module CI


on:
  push:
    branches:
      - master
      - dev
      - feature/#279
  pull_request:
    branches:
      - master
      - dev

jobs:
  eureka:
    runs-on: ubuntu-latest
    steps:
      - name: 소스 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Eureka 서버 빌드
        run: |
          -jar com.devsquad10.eureka/build/libs/*.jar & 
           sleep 20 # Eureka 서버가 시작될 때까지 잠시 대기 (시간 조정 가능)
