name: 이선좌 - Multi-Module CI
on:
  push:
    branches:
      - master
      - dev
      - feature/#327
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    name: Multi-Module Build & Docker Push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - com.taken_seat.eureka-service
          - com.taken_seat.common-service
          - com.taken_seat.auth-service
          - com.taken_seat.coupon-service
          - com.taken_seat.queue-service
          - com.taken_seat.booking-service
          - com.taken_seat.performance-service
          - com.taken_seat.payment-service
          - com.taken_seat.review-service
          - com.taken_seat.gateway-service
      fail-fast: false
      max-parallel: 5

    steps:
      - name: 소스 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle 실행 권한 부여
        run: chmod +x ./gradlew

      - name: 환경 변수 설정
        run: |
          echo "SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_DRIVER_CLASS_NAME=${{ secrets.SPRING_DATASOURCE_DRIVER_CLASS_NAME }}" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "LOKI_URL=${{ secrets.LOKI_URL }}" >> $GITHUB_ENV

      - name: Gradle 빌드 (서비스 모듈)
        run: ./gradlew :${{ matrix.module }}:build --parallel --no-daemon

      - name: Docker 로그인 (GitHub Container Registry)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.MY_GITHUB_USERNAME }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Docker 이미지 빌드 및 푸시
        run: |
          ORG_NAME=${{ secrets.MY_GITHUB_USERNAME }}  # GitHub 계정명
          MODULE_NAME=$(basename "${{ matrix.module }}" | sed 's/com.taken_seat.//')  # com.taken_seat 부분을 제거
          MODULE_PATH=${{ matrix.module }}
          
            MODULE_NAME=$(echo $MODULE_NAME | tr '-' '.')
          
          IMAGE_NAME=ghcr.io/${ORG_NAME}/${MODULE_NAME}:latest

          docker build -t $IMAGE_NAME -f $MODULE_PATH/Dockerfile $MODULE_PATH
          docker push $IMAGE_NAME