name: 이선좌 - Multi-Module CI
on:
  push:
    branches:
      - master
      - dev
      - feature/#327
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    name: Multi-Module Build
    runs-on: ubuntu-latest


    steps:
      - name: 소스 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle 실행 권한 부여
        run: chmod +x ./gradlew

      - name: 환경 변수 설정
        run: |
          echo "SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_DRIVER_CLASS_NAME=${{ secrets.SPRING_DATASOURCE_DRIVER_CLASS_NAME }}" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "LOKI_URL=${{ secrets.LOKI_URL }}" >> $GITHUB_ENV

      - name: 전체 모듈 빌드 (병렬 처리)
        run: ./gradlew build --parallel --no-daemon
          
          
