name: 이선좌 - Multi-Module CI
on:
  push:
    branches:
      - master
      - dev
      - feature/#279
  pull_request:
    branches:
      - master
      - dev

jobs:
  eureka:
    runs-on: ubuntu-latest
    steps:
      - name: 소스 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Eureka 서버 빌드
        run: |
          ./gradlew :com.taken_seat.eureka-service:bootJar


  services:
    runs-on: ubuntu-latest
    needs: eureka  # Eureka가 실행된 후 실행
    strategy:
      matrix:
        module:
          - com.taken_seat.common-service
          - com.taken_seat.auth-service
          - com.taken_seat.coupon-service
          - com.taken_seat.queue-service
          - com.taken_seat.booking-service
          - com.taken_seat.performance-service
          - com.taken_seat.payment-service
          - com.taken_seat.review-service
      fail-fast: false
      max-parallel: 5

    steps:
      - name: 소스 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle 실행 권한 부여
        run: chmod +x ./gradlew

      - name: 환경 변수 설정
        run: |
          echo "SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_DRIVER_CLASS_NAME=${{ secrets.SPRING_DATASOURCE_DRIVER_CLASS_NAME }}" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "LOKI_URL=${{ secrets.LOKI_URL }}" >> $GITHUB_ENV

      - name: Gradle 빌드 (서비스 모듈)
        run: ./gradlew :${{ matrix.module }}:build --parallel --no-daemon

  gateway:
    runs-on: ubuntu-latest
    needs: services  # 모든 서비스 모듈이 빌드된 후 실행
    steps:
      - name: 소스 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Gradle 빌드 (Gateway)
        run: ./gradlew :com.taken_seat.gateway-service:build --no-daemon